services:
  frontend:
    env_file: ".env"
    image: node:latest
    build: ./conduit-frontend
    ports:
      - "8282:80"
    restart: on-failure

  backend:
    env_file: ".env"
    image: python:latest
    build: ./conduit-backend
    volumes:
      - conduit-db:/app/db_data
    ports:
      - "8280:8000"
    restart: on-failure

volumes:
  conduit-db: